DSND-1566: Simplify charges processing
companieshouse/company-metrics-consumer pull request #53
Opened 2023-11-23 18:51 UTC by crowlandsCH

* Tested locally
* Pom up to date

[DSND-1566](https://companieshouse.atlassian.net/browse/DSND-1566)

2023-11-24 08:50 UTC, cgregoryCH requested changes
Looks great, just one test case I think should be reconsidered and BaseApiClientService.java can now be removed as its unused.

2023-11-24 08:50 UTC, cgregoryCH commented on src/test/java/uk/gov/companieshouse/company/metrics/service/MetricsClientFactoryTest.java
> -    @DisplayName("Metrics factory correctly returns a deleted charges client")
This is still a valid test as it covers the deleted scenario, even though its the same charges client.

2023-11-27 10:30 UTC, cgregoryCH approved these changes

2023-11-27 10:32 UTC, sthompsonCH approved these changes

2023-11-27 11:35 UTC, merged